#ifndef COLORS_H_
#define COLORS_H_

typedef enum color_t {
    COLOR_DEFAULT,
    COLOR_RED_BLACK,
    COLOR_GREEN_BLACK,
    COLOR_YELLOW_BLACK,
    COLOR_BLUE_BLACK,
    COLOR_MAGENTA_BLACK,
    COLOR_CYAN_BLACK,
    COLOR_WHITE_BLACK,
} color_t;

#endif // COLORS_H_