#ifndef COLOR_H_
#define COLOR_H_

/***[Includes]****************************************************************/

/***[Macros]******************************************************************/
#define COLOR_NEGATE(color) (0xFF - ((color) & 0xFF))
#define COLOR_INVERTED(color) COLOR_NEGATE

/***[Types]*******************************************************************/

/** @brief All possible color pairs, as COLOR_<FOREGROUND>_<BACKGROUND> */
typedef enum color_t {
    COLOR_DEFAULT = 0,

    COLOR_BLACK_BLACK,
    COLOR_BLACK_RED,
    COLOR_BLACK_GREEN,
    COLOR_BLACK_YELLOW,
    COLOR_BLACK_BLUE,
    COLOR_BLACK_MAGENTA,
    COLOR_BLACK_CYAN,
    COLOR_BLACK_WHITE,

    COLOR_RED_RED,
    COLOR_RED_GREEN,
    COLOR_RED_YELLOW,
    COLOR_RED_BLUE,
    COLOR_RED_MAGENTA,
    COLOR_RED_CYAN,
    COLOR_RED_WHITE,

    COLOR_GREEN_GREEN,
    COLOR_GREEN_YELLOW,
    COLOR_GREEN_BLUE,
    COLOR_GREEN_MAGENTA,
    COLOR_GREEN_CYAN,
    COLOR_GREEN_WHITE,

    COLOR_YELLOW_YELLOW,
    COLOR_YELLOW_BLUE,
    COLOR_YELLOW_MAGENTA,
    COLOR_YELLOW_CYAN,
    COLOR_YELLOW_WHITE,

    COLOR_BLUE_BLUE,
    COLOR_BLUE_MAGENTA,
    COLOR_BLUE_CYAN,
    COLOR_BLUE_WHITE,

    COLOR_MAGENTA_MAGENTA,
    COLOR_MAGENTA_CYAN,
    COLOR_MAGENTA_WHITE,

    COLOR_CYAN_CYAN,
    COLOR_CYAN_WHITE,

    COLOR_WHITE_WHITE,

    COLOR_RED_BLACK = COLOR_NEGATE(COLOR_BLACK_RED),
    COLOR_GREEN_BLACK = COLOR_NEGATE(COLOR_BLACK_GREEN),
    COLOR_YELLOW_BLACK = COLOR_NEGATE(COLOR_BLACK_YELLOW),
    COLOR_BLUE_BLACK = COLOR_NEGATE(COLOR_BLACK_BLUE),
    COLOR_MAGENTA_BLACK = COLOR_NEGATE(COLOR_BLACK_MAGENTA),
    COLOR_CYAN_BLACK = COLOR_NEGATE(COLOR_BLACK_CYAN),
    COLOR_WHITE_BLACK = COLOR_NEGATE(COLOR_BLACK_WHITE),

    COLOR_GREEN_RED = COLOR_NEGATE(COLOR_RED_GREEN),
    COLOR_YELLOW_RED = COLOR_NEGATE(COLOR_RED_YELLOW),
    COLOR_BLUE_RED = COLOR_NEGATE(COLOR_RED_BLUE),
    COLOR_MAGENTA_RED = COLOR_NEGATE(COLOR_RED_MAGENTA),
    COLOR_CYAN_RED = COLOR_NEGATE(COLOR_RED_CYAN),
    COLOR_WHITE_RED = COLOR_NEGATE(COLOR_RED_WHITE),

    COLOR_YELLOW_GREEN = COLOR_NEGATE(COLOR_GREEN_YELLOW),
    COLOR_BLUE_GREEN = COLOR_NEGATE(COLOR_GREEN_BLUE),
    COLOR_MAGENTA_GREEN = COLOR_NEGATE(COLOR_GREEN_MAGENTA),
    COLOR_CYAN_GREEN = COLOR_NEGATE(COLOR_GREEN_CYAN),
    COLOR_WHITE_GREEN = COLOR_NEGATE(COLOR_GREEN_WHITE),

    COLOR_BLUE_YELLOW = COLOR_NEGATE(COLOR_YELLOW_BLUE),
    COLOR_MAGENTA_YELLOW = COLOR_NEGATE(COLOR_YELLOW_MAGENTA),
    COLOR_CYAN_YELLOW = COLOR_NEGATE(COLOR_YELLOW_CYAN),
    COLOR_WHITE_YELLOW = COLOR_NEGATE(COLOR_YELLOW_WHITE),

    COLOR_MAGENTA_BLUE = COLOR_NEGATE(COLOR_BLUE_MAGENTA),
    COLOR_CYAN_BLUE = COLOR_NEGATE(COLOR_BLUE_CYAN),
    COLOR_WHITE_BLUE = COLOR_NEGATE(COLOR_BLUE_WHITE),

    COLOR_CYAN_MAGENTA = COLOR_NEGATE(COLOR_MAGENTA_CYAN),
    COLOR_WHITE_MAGENTA = COLOR_NEGATE(COLOR_MAGENTA_WHITE),

    COLOR_WHITE_CYAN = COLOR_NEGATE(COLOR_CYAN_WHITE),

} color_t;

/***[Extern variables]********************************************************/

/***[Functions prototypes]****************************************************/

/**
 * @brief Initializes all color pairs defined in the color_t enumeration.
 */
void color_init(void);

#endif // COLOR_H_
